# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyACM0
baud: 57600
timeout: 0.1

rate: 50
sensor_state_rate: 10

use_base_controller: True
base_controller_rate: 10

publish_tf: True

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_footprint

# === Robot drivetrain parameters
# wheel_diameter: 0.146
# wheel_track: 0.2969
wheel_diameter: 0.34
wheel_track: 0.52
encoder_resolution: 3200
#gear_reduction: 32
motors_reversed: True

# === PID parameters
Kp: 10
Kd: 12
Ki: 0
Ko: 50
#accel_limit: 1.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * PointCloudPing
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage



sensors: {
  sonar_front_center:   {pin: 28, echopin: 30, type: Ping, rate: 10,frame_id: 1},
  sonar_left_center:   {pin: 34, echopin: 36, type: Ping, rate: 10,frame_id: 2},
  sonar_right_center:   {pin: 46, echopin: 48, type: Ping, rate: 10,frame_id: 3},

  # sonar_front_center:   {pin: 28, echopin: 30, type: PointCloudPing, rate: 5, frame_id: 1},
  # sonar_left_center:   {pin: 34, echopin: 36, type: PointCloudPing, rate: 5,frame_id: 2},
  # sonar_right_center:   {pin: 46, echopin: 48, type: PointCloudPing, rate: 5,frame_id: 3},

  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  #arduino_led:          {pin: 13, type: Digital, rate: 5, direction: output}
}
